name: Build and deliver container

on: push

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      
      -
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - 
        name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build and Push
        run: docker buildx build --platform linux/amd64,linux/arm64 ${{ secrets.DOCKER_USER }}/portfolio:latest --push .
